### ISSUE TITLE
App not building

### ISSUE THREAD

**Issue by moh1122** [grachyov/Reminders-on-Apple-Watch#1]
Hello
Great proj
But its not building i run the pod install and opened .xworkspace but when building its saying access denied any clue?

**Comment by grachyov** [comment]
Sorry for this inconvenience, I'll investigate.

**Comment by moh1122** [comment]
thnk u for your quick reply awaiting your update
thnk u

**Comment by grachyov** [comment]
I moved Pods with Fabric to the separate branch. Can you please try to build master branch now?
